Repository ese111/airbnb, pull requests merged in 2022-05, with the labels that each got.

#4 feat: 엔티티 만들기
  BE/.idea/uiDesigner.xml
  BE/src/main/java/yanse/airbnb/domain/hotel/Address.java
  BE/src/main/java/yanse/airbnb/domain/hotel/Room.java
  BE/src/main/java/yanse/airbnb/domain/hotel/RoomInfo.java
  BE/src/main/java/yanse/airbnb/domain/member/Member.java
  BE/src/main/java/yanse/airbnb/domain/reservation/Reservation.java
  BE/src/main/java/yanse/airbnb/domain/wish/WishList.java
Labels: feature

#6 chore: gitignore 추가
  BE/.gitignore
  BE/.gradle/7.4.1/checksums/checksums.lock
  BE/.gradle/7.4.1/checksums/md5-checksums.bin
  BE/.gradle/7.4.1/checksums/sha1-checksums.bin
  BE/.gradle/7.4.1/dependencies-accessors/dependencies-accessors.lock
  BE/.gradle/7.4.1/dependencies-accessors/gc.properties
  BE/.gradle/7.4.1/executionHistory/executionHistory.lock
  BE/.gradle/7.4.1/fileChanges/last-build.bin
  BE/.gradle/7.4.1/fileHashes/fileHashes.lock
  BE/.gradle/7.4.1/gc.properties
  BE/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  BE/.gradle/buildOutputCleanup/cache.properties
  BE/.gradle/vcs-1/gc.properties
  BE/.idea/.gitignore
  BE/.idea/.name
  BE/.idea/compiler.xml
  BE/.idea/gradle.xml
  BE/.idea/jarRepositories.xml
  BE/.idea/misc.xml
  BE/.idea/uiDesigner.xml
  BE/.idea/vcs.xml
  BE/HELP.md
  BE/out/production/classes/yanse/airbnb/AirbnbApplication.class
  BE/out/production/resources/application.yml
Labels: chore

#14 [Android] feat: compose로 home 구현
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/team16/airbnb/data/NearInfo.kt
  Android/app/src/main/java/com/team16/airbnb/ui/HomeFragment.kt
Labels: Android

#16 refactor: 리뷰받은 내용 및 부족한 부분 추가
  BE/src/main/java/yanse/airbnb/domain/hotel/RoomInfo.java
  BE/src/main/java/yanse/airbnb/domain/main/ImageType.java
  BE/src/main/java/yanse/airbnb/domain/main/MainAroundImage.java
  BE/src/main/java/yanse/airbnb/domain/main/MainImage.java
  BE/src/main/java/yanse/airbnb/domain/main/MainRecommendationImage.java
  BE/src/main/java/yanse/airbnb/domain/member/Member.java
  BE/src/main/java/yanse/airbnb/domain/reservation/DetailFee.java
  BE/src/main/java/yanse/airbnb/domain/reservation/DiscountPolicy.java
  BE/src/main/java/yanse/airbnb/domain/reservation/Reservation.java
  BE/src/main/java/yanse/airbnb/domain/room/Address.java
  BE/src/main/java/yanse/airbnb/domain/room/Room.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomInfo.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomType.java
  BE/src/main/java/yanse/airbnb/domain/wish/WishList.java
Labels: refactor, BE

#19 [Andorid] search view 제작 중
  Android/app/src/main/java/com/team16/airbnb/ui/HomeFragment.kt
  Android/app/src/main/java/com/team16/airbnb/ui/search/SearchFragment.kt
  Android/app/src/main/res/drawable/ic_back.xml
  Android/app/src/main/res/drawable/ic_close.xml
  Android/app/src/main/res/layout/fragment_search.xml
  Android/app/src/main/res/layout/item_search_area.xml
  Android/app/src/main/res/layout/item_search_description.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/themes.xml
Labels: Android

#23 feat: DB예약어인 변수명 변경, RoomImage 엔티티 생성 및 데이터 생성
  BE/src/main/java/yanse/airbnb/domain/image/Image.java
  BE/src/main/java/yanse/airbnb/domain/image/RoomImage.java
  BE/src/main/java/yanse/airbnb/domain/member/Members.java
  BE/src/main/java/yanse/airbnb/domain/reservation/DetailFee.java
  BE/src/main/java/yanse/airbnb/domain/reservation/Reservation.java
  BE/src/main/java/yanse/airbnb/domain/room/Address.java
  BE/src/main/java/yanse/airbnb/domain/room/Room.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomInfo.java
  BE/src/main/java/yanse/airbnb/domain/wish/Wish.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
Labels: BE
